
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="中智信智慧社区,智慧社区,厦门智慧社区">
    <meta name="author" content="">
    <link rel="icon" href="<?php echo $this->baseUrl("/static/images/favicon.jpg")?>">

    <title>中智信智慧社区</title>

    <!-- Bootstrap core CSS -->
    <?php echo $this->headLink();?>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body data-spy="scroll" data-target="#navbar_zzx">
    <div class="wrap">
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar_zzx" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">eMegasys智慧社区管理系统-中智信智慧社区</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-logo"></span>&nbsp;中智信智慧社区</a>
        </div>
        <div id="navbar_zzx" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#ourcompay">公司介绍</a></li>
            <li><a href="#ournews">新闻动态</a></li>
            <li><a href="#ourproducts">产品中心与解决方案</a></li>
            <li><a href="#ourprojects">成功案例</a></li>
            <li><a href="#joinus">加入我们</a></li>
<!--             <li><a href="//www.xmcii.com" target="_blank">关于我们</a></li> -->
<!--             <li><a href="#">在线帮助</a></li> -->
         </ul>
        </div><!--/.nav-collapse -->
      </div>          
    </nav>
	<div class="container-fluid">
	  <div class="row row-item">
	   <!-- Carousel
    ================================================== -->
		    <div id="myCarousel" class="carousel slide" data-ride="carousel">
		      <!-- Indicators -->
		      <ol class="carousel-indicators">
		        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		        <li data-target="#myCarousel" data-slide-to="1"></li>
		        <li data-target="#myCarousel" data-slide-to="2"></li>
		        <li data-target="#myCarousel" data-slide-to="3"></li>
		        <li data-target="#myCarousel" data-slide-to="4"></li>
		      </ol>
		      <div class="carousel-inner" role="listbox">
		        <div class="item active">
		          <a href="#"><img src="<?php echo $this->baseUrl("/static/images/banner_1.jpg");?>" alt="First slide"></a>
<!-- 		          <div class="container"> -->
<!-- 		            <div class="carousel-caption"> -->
<!-- 		              <h1>中智信智慧社区</h1> -->
<!-- 		              <p>eMegasys智慧社区</p> -->
<!-- 		            </div> -->
<!-- 		          </div> -->
		        </div>
		        <div class="item">
		          <a href="<?php echo $this->baseUrl("/demo/sqgl");?>"><img src="<?php echo $this->baseUrl("/static/images/banner_2.jpg");?>" alt="Second slide"></a>
		          <!--<div class="container">
		            <div class="carousel-caption">
		              <h1>Another example headline.</h1>
		              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
		            </div>
		          </div> -->
		        </div>
		        <div class="item">
		          <a href="<?php echo $this->baseUrl("/demo/jzgl");?>"><img src="<?php echo $this->baseUrl("/static/images/banner_3.jpg");?>" alt="Third slide"></a>
		        </div>
		        <div class="item">
		          <a href="<?php echo $this->baseUrl("/demo/shfw");?>"><img src="<?php echo $this->baseUrl("/static/images/banner_4.jpg");?>" alt="Four slide"></a>
		        </div>
		        <div class="item">
		          <a href="<?php echo $this->baseUrl("/demo/shfw");?>"><img src="<?php echo $this->baseUrl("/static/images/banner_3.jpg");?>" alt="Five slide"></a>
		        </div>
		      </div>
		      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
		        <span class="glyphicon glyphicon-chevron-left"></span>
		        <span class="sr-only">Previous</span>
		      </a>
		      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
		        <span class="glyphicon glyphicon-chevron-right"></span>
		        <span class="sr-only">Next</span>
		      </a>
		    </div><!-- /.carousel -->
	  </div>
</div>
<div class="container"> 
	<div class="row row-item" id="ourcompay">
	   <h2>我们做什么</h2>
	   <h3>公司资质</h3>
<!-- 	   <p>1、软件企业认定证书  </p> -->
	   <div class="col-lg-4 zhengshu">          
          <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/ruanjianqiyerending_01.jpg');?>">
        </div>
        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/ruanjianqiyerending_02.jpg');?>">
        </div>
        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/ruanjiachanpindengji_01.jpg');?>">
        </div>
        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/ruanjiachanpindengji_02.jpg');?>">
        </div>
        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/jishumaoyijigou.jpg');?>">
        </div>
        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/jienengxiehui.jpg');?>">
        </div>
        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/ruanjianzhuzuo.jpg');?>">
        </div>
        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/ruanjianzhuzuo_01.jpg');?>">
        </div>
        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/ruanjianzhuzuo_02.jpg');?>">
        </div>
        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/ruanjianzhuzuo_03.jpg');?>">
        </div>
        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/ruanjianzhuzuo_04.jpg');?>">
        </div>
         <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/ruanjianzhuzuo_05.jpg');?>">
        </div>
         <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/ruanjianzhuzuo_06.jpg');?>">
        </div>
        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/ruanjianzhuzuo_07.jpg');?>">
        </div>
        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/ceshibaogao.jpg');?>">
        </div>
        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/pmp.jpg');?>">
        </div>

        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/wulianwang.jpg');?>">
        </div>
        <div class="col-lg-4 zhengshu">
            <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/zhengshu/xinjiangshanghui.jpg');?>">
        </div>
	</div>
	<div class="row row-item" id="ournews">
	   <h2>新闻动态</h2>
	   <div class="col-lg-4">
          <h3>Safari bug warning!</h3>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-lg-4">
          <h3>Safari bug warning!</h3>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-lg-4">
          <h3>Safari bug warning!</h3>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
	</div>
	<div class="row row-item" id="ourproducts">
	   <h2>产品中心与解决方案</h2>
	   <div class="col-lg-4">
	      <p style="font-size: 100px;"><span class="glyphicon glyphicon-camera"></span></p>
          <h3>Safari bug warning!</h3>          
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-lg-4">
          <p style="font-size: 100px;"><span class="glyphicon glyphicon-facetime-video"></span></p>
          <h3>Safari bug warning!</h3>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-lg-4">
          <p style="font-size: 100px;"><span class="glyphicon glyphicon-picture"></span></p>
          <h3>Safari bug warning!</h3>          
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
	</div>
	<div class="row row-item" id="ourprojects">
	   <h3>成功案例（公共建筑、商业地产、办公大楼、五星酒店）</h3>
	   <div class="col-lg-4">
          <h4>福州海峡国际会展中心</h4>
          <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/ggjz_01.jpg');?>">
          <p class="text-danger">福州海峡国际会展中心位于福州市仓山区会展岛，是目前国内最大单体会展中心之一，也是亚洲第二大会展中心。项目主要包含了楼控、监控等九个系统，总点量超过100,000点。集成平台采用分布式部署方式，使用了高速I/O通道、监听服务等系统组件及服务，达到动态负载均衡，更好的保证平台的稳定运行。集成平台的运用，更好的帮助了业主方在视频跟踪、设备控制等方面更好的贯通运用；特别是在重大展会、会议期间协调各种重要事件及相关报警的及时处理、及时跟踪。</p>
        </div>
	   <div class="col-lg-4">
          <h4>龙岩会展中心</h4>
          <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/ggjz_02.jpg');?>">
          <p class="text-danger">龙岩会展中心位于龙岩市新罗区。项目主要包含了楼控、监控、防盗、门禁、照明等系统。</p>
        </div>
	   <div class="col-lg-4">
          <h4>漳州市正兴医院</h4>
          <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/ggjz_03.jpg');?>">
          <p class="text-danger"> 漳州市正兴医院位于漳州市芗城区北环城路。项目主要包含了楼宇、安防、消防、一卡通、智能照明等系统。</p>
        </div>
	   <div class="col-lg-4">
          <h4>厦门海峡交流中心1#楼</h4>
          <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/ggjz_04.jpg');?>">
          <p class="text-danger">海峡交流中心位于厦门本岛东部，国际会展中心北侧，随着周边国际会议中心、五星级度假酒店、领事馆区、高档大型居住区、厦门国际旅游中心、闽南戏曲艺术剧院、国际游艇码头、国际网球中心等一系列高标准项目的相继建成，本区域将逐步成为集高档居住区、现代化会议展览、办公、商业娱乐、酒店为一体的现代化生态型滨海景观城区，为厦门未来海湾型城市一个非常重要的标志性建筑群。项目总建设用地面积约8.65公顷，地上总建筑面积约45万平方米，地下建筑面积约24万平方米。</p>
          <p class="text-danger">海峡交流中心集成平台主要包括楼宇自控系统、闭路监控系统、防盗报警系统、出入口控制系统、停车场管理系统、智能卡系统、消防报警及公共广播系统、多媒体信息显示系统、智能照明系统、室外立面照明系统、冷源群控系统、变配电系统、发电机组系统、电梯集控系统等。集成平台使用了高速I/O通道、批量点位读取、监听服务等系统组件及服务，更好的支持平台的稳定运行。</p>
        </div>
        <div class="col-lg-4">
          <h4>福清三农大厦</h4>
          <img class="img-responsive"src="<?php echo $this->baseUrl('/static/images/ggjz_05.jpg');?>">
          <p class="text-danger">福清三农大厦位于福清市宏路街道洋埔村，建筑面积38000平方米,包含市民服务中心、农业服务中心、林业科技服务中心、海洋和渔业服务中心、民政办证窗口。</p>
          <p class="text-danger">福清三农大厦集成项目主要包含了楼宇自控系统、视频监控系统、电子巡更系统、一卡通系统、信息发布系统、防盗报警系统等。采用B/S平台架构，将各个子系统无缝集成于同一平台，实现对各设备子系统进行统一的监测、控制、管理，准确、快速、全面地反应各子系统的运行状态；联动预案自定义配置功能的应用，在该项目中实现了跨子系统联动的前提下更是节省了人力，同时也提高了对突发事件进行快速响应的能力；时间调度配置及报表等功能的应用，在满足用户要求的前提下更是达到了综合节能和方便管理。</p>
        </div>
	</div>
	<div class="row row-item" id="joinus">
	    <h2>加入我们</h2>
	    <div class="col-lg-4">
            <p><img class="img-responsive" style="max-width: 200px;" src="<?php echo $this->baseUrl('/static/images/QR_Code.png');?>"></p>

        </div>
        <div class="col-lg-4">
             <address>
                  <strong>客服中心&nbsp; SERVICE CENTER</strong><br>
                                      电话：0592-5033905 5033910<br>
                                     传真：0592-5033915<br>
                </address>
        </div>
        <div class="col-lg-4">        
          <address><strong>联系方式</strong><br>
          <abbr>地址：厦门市湖滨南路811号1406#</abbr><br>
          <abbr>邮箱：hr@xmcii.com</abbr><br>
          <abbr>网址：www.xmcii.com</abbr><br>
          <abbr>电话：0592-5033905 5033910</abbr><br>
          <abbr>传真：0592-5033915</abbr><br>
          <abbr>邮编：361000</abbr><br>
          </address>
        </div>
   </div>
   <div class="row row-item" id="employer">
        <h4><strong>招聘信息(与公司现阶段需要的各种人才要求)</strong></h4>
        <div class="col-lg-4">
            <h5 class="text-warning"><strong>一、工程部软件工程师</strong></h5>
            <p><b>职位基本要求</b></p>
            <p>学历要求： 本科以上</p>
            <p>性别要求： 不限</p>
            <p>职位性质： 全职</p>
            <p>专业要求： 计算机技术、软件技术及相关专业</p>
            <p>工作地点： 厦门市</p>
            <p><b>工作职责：</b></p>
            <ol>
                <li>智能楼宇集成项目的现场安装与实施</li>
                <li>软件集成平台的现场支持与技术问题反馈</li>
                <li> 项目初期的实施需求调研</li>
            </ol>            
            <p><b>任职资格：</b></p>
            <ol>
            <li>熟悉常见计算机网络架构</li>
            <li> 熟悉SQLServer等常见数据库的安装与维护</li>
            <li>能够顺利阅读英文技术文档</li>
            <li> 能够快速理解客户需求</li>
            <li> 具有良好的学习能力，团队意识强</li>
            <li>熟悉智能楼宇集成行业背景者优先</li>
            <li> 熟悉OPC、bacnet等智能楼宇常见协议者优先</li>
            <li> 有组态软件使用经验者优先</li>
            </ol>
        </div>
        <div class="col-lg-4">
            <h5 class="text-warning"><strong>二、.NET程序员</strong></h5>
            <p><b>职位基本要求</b></p>
            <p>学历要求： 本科以上</p>
            <p>性别要求： 不限</p>
            <p>职位性质： 全职</p>
            <p>招聘对象： 一年工作经验以上</p>
            <p>专业要求： 计算机技术、软件技术及相关专业</p>
            <p>工作地点： 厦门市</p>
            <p><b>工作职责：</b></p>
            <ol>
                <li>公司集成软件平台的子模块开发</li>
                <li>智能楼宇集成项目基于平台的二次开发</li>
                <li>内部IT系统的开发</li>
                <li>为实施工程师提供技术支持</li>
            </ol>            
            <p><b>任职资格：</b></p>
            <ol>
                <li>熟悉.Net技术，熟悉Silverlight/WPF开发，一年以上C#开发经验</li>
                <li>熟悉C/S架构，B/S架构</li>
                <li>了解Windows服务的开发</li>
                <li>能够顺利阅读英文技术文档</li>
                <li>具有良好的自学习能力，热爱编程，团队意识强</li>
                <li>熟悉DevExpress控件者优先</li>
                <li>了解svn等源码管理工具者优先</li>
                <li>熟悉OPC、bacnet等智能楼宇常见协议者优先</li>            
            </ol>
        </div>
        <div class="col-lg-4">
            <h5 class="text-warning"><strong>三、研发部高级程序员</strong></h5>
            <p><b>职位基本要求</b></p>
            <p>学历要求： 本科以上</p>
            <p>性别要求： 不限</p>
            <p>职位性质： 全职</p>
            <p>招聘对象： 三年工作经验以上</p>
            <p>专业要求： 计算机技术、软件技术及相关专业</p>
            <p>工作地点： 厦门市</p>
            <p><b>工作职责： </b></p>
            <ol>
                <li>公司集成软件平台的设计与升级</li>
                <li>智能楼宇集成项目系统设计与技术攻关</li>
                <li>研发与平台对接的接口协议模块</li>
                <li>公司开发规范的制定与完善</li>
                <li>为程序员提供技术培训</li>
                <li>为产品规划提供技术支持</li>
            </ol>
            <p><b>任职资格：</b></p>
            <ol>
                <li>熟悉.Net技术，三年以上C#团队开发经验</li>
                <li>熟悉C/S架构，B/S架构，有框架开发经验</li>
                <li>熟悉设计模式，理解O/RM、IoC、AOP等软件设计思想</li>
                <li>了解软件开发的过程，能够把握软件开发进度</li>
                <li>熟悉svn等源码管理工具</li>
                <li>能够顺利阅读英文技术文档</li>
                <li>具有良好的自学习能力，热爱编程，团队意识强</li>
                <li>有COM+/DCOM开发经验优先</li>
                <li>熟悉OPC、bacnet等智能楼宇常见协议优先</li>
                <li>熟悉JIRA或Redmine等项目管理工具者优先</li>
                <li>熟悉WPF优先</li>
            </ol>
        </div>
        <div class="col-lg-4">
            <h5 class="text-warning"><strong>四、商业运作专员（Commercial Operation Department）</strong></h5>  
            <p><b>职位基本要求</b></p>
            <p>学历要求： 大专以上</p>
            <p>性别要求： 不限</p>
            <p>职位性质： 全职</p>
            <p>工作地点： 厦门市</p>
            <p><b>工作职责：</b></p>
            <ol>
                <li>内部控制：协助部门领导，对研发和实施团队任务的进度、交付成果进行监督；</li>
                <li>文档管理：协助信息部门领导，负责公司知识库的日常维护和整理工作。</li>
                <li>客户服务：客户沟通、软件授权等。</li>
                <li>负责职责内各类文档起草整理工作。</li>
                <li>负责公司网站的管理和维护。</li>
                <li>领导交付的其它工作。</li>
            </ol>
            <p><b>任职资格：</b></p>
            <ol>
                <li>大专及以上学历，计算机软件等相关专业；</li>
                <li>一年以上的工作经验；</li>
                <li>较强的工作责任感，沟通能力强；</li>
            </ol>
        </div>   
        <div class="col-lg-4">
            <h5 class="text-warning"><strong>五、销售工程师 </strong></h5>
            <p><b>职位基本要求</b></p>
            <p>学历要求： 大专以上</p>
            <p>性别要求： 不限</p>
            <p>职位性质： 全职</p>
            <p>工作地点： 厦门市</p>
            <p><b>工作职责：</b></p>
            <ol>
            <li>执行公司市场策略，完成市场目标；</li>
            <li>负责开发和管理经销渠道；</li>
            <li>根据客户的要求，提供初步的系统选型报价及技术解决方案；</li>
            <li>访问项目客户，准确收集项目信息；</li>
            <li>根据计划组织市场推广活动；</li>
            </ol>
            <p><b>任职资格：</b></p>
            <ol>
            <li>大专及以上学历，计算机软件、建筑智能化、自动控制、机电一体化等相关专业最佳；</li>
            <li>较强的工作责任感，沟通能力强；</li>
            <li>有一定的英语阅读水平。</li>
            </ol>
         </div>   
         <div class="col-lg-4">
            <h5 class="text-warning"><strong>六、区域销售经理 </strong></h5>
            <p><b>职位基本要求</b></p>
            <p>学历要求： 大专以上</p>
            <p>性别要求： 不限</p>
            <p>职位性质： 全职</p>
            <p>工作地点： 厦门市</p>
            <p><b>工作职责：</b></p>
            <ol><li>负责公司产品的销售与公司品牌推广；</li>
            <li>执行公司市场策略，完成市场目标；</li>
            <li>负责开发和管理经销渠道；
            <li>根据客户的要求，提供初步的系统选型报价及技术解决方案；</li>
            <li>访问项目客户，准确收集项目信息；</li>
            <li>根据计划组织市场推广活动；</li>
            <li>协调客户和工程、客服的项目关系；</li>
            </ol>
            <p><b>任职资格：</b></p>
            <ol>
            <li>大专及以上学历，计算机软件、建筑智能化、自动控制、机电一体化等相关专业最佳；</li>
            <li>两年以上的工作经验；</li>
            <li>较强的工作责任感，沟通能力强；</li>
            <li>有一定的英语阅读水平。</li>
            </ol>           
	   </div>
	</div>
    <div class="row">
			      <!-- Site footer -->
	     <div id="footer" class="container">
	     <hr>
	        <div class="col-md-12">
	            <p>地址：厦门市湖滨南路811号1406# | 电话：0592-5033905 5033910 | 传真：0592-5033915</p>
	            <p>&copy; 2015 厦门中智信系统集成有限公司 All Right Servered 闽ICP备10007796号</p>
	        </div>      

	     </div>
      </div>
    </div>
 </div>

    <?php echo $this->headScript();?>
  </body>
</html>