
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="中智信智慧社区,智慧社区,厦门智慧社区">
    <meta name="author" content="">
    <link rel="icon" href="<?php echo $this->baseUrl("/static/images/favicon.jpg")?>">

    <title>中智信智慧社区</title>

    <!-- Bootstrap core CSS -->
    <?php echo $this->headLink();?>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body data-spy="scroll" data-target="#navbar_zzx">
    <div class="wrap">
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">eMegasys智慧社区管理系统-中智信智慧社区</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-logo"></span>&nbsp;eMegasys智慧社区管理系统---中智信智慧社区</a>
        </div>
        <div id="navbar_zzx" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#ourcompay">公司介绍</a></li>
            <li><a href="#ournews">新闻动态</a></li>
            <li><a href="#ourproducts">产品中心与解决方案</a></li>
            <li><a href="#ourprojects">成功案例</a></li>
            <li><a href="#joinus">加入我们</a></li>
<!--             <li><a href="//www.xmcii.com" target="_blank">关于我们</a></li> -->
<!--             <li><a href="#">在线帮助</a></li> -->
         </ul>
        </div><!--/.nav-collapse -->
      </div>          
    </nav>
	<div class="container-fluid">
	  <div class="row row-item">
	   <!-- Carousel
    ================================================== -->
		    <div id="myCarousel" class="carousel slide" data-ride="carousel">
		      <!-- Indicators -->
		      <ol class="carousel-indicators">
		        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		        <li data-target="#myCarousel" data-slide-to="1"></li>
		        <li data-target="#myCarousel" data-slide-to="2"></li>
		        <li data-target="#myCarousel" data-slide-to="3"></li>
		        <li data-target="#myCarousel" data-slide-to="4"></li>
		      </ol>
		      <div class="carousel-inner" role="listbox">
		        <div class="item active">
		          <a href="#"><img src="<?php echo $this->baseUrl("/static/images/banner_1.jpg");?>" alt="First slide"></a>
<!-- 		          <div class="container"> -->
<!-- 		            <div class="carousel-caption"> -->
<!-- 		              <h1>中智信智慧社区</h1> -->
<!-- 		              <p>eMegasys智慧社区</p> -->
<!-- 		            </div> -->
<!-- 		          </div> -->
		        </div>
		        <div class="item">
		          <a href="<?php echo $this->baseUrl("/demo/sqgl");?>"><img src="<?php echo $this->baseUrl("/static/images/banner_2.jpg");?>" alt="Second slide"></a>
		          <!--<div class="container">
		            <div class="carousel-caption">
		              <h1>Another example headline.</h1>
		              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
		            </div>
		          </div> -->
		        </div>
		        <div class="item">
		          <a href="<?php echo $this->baseUrl("/demo/jzgl");?>"><img src="<?php echo $this->baseUrl("/static/images/banner_3.jpg");?>" alt="Third slide"></a>
		        </div>
		        <div class="item">
		          <a href="<?php echo $this->baseUrl("/demo/shfw");?>"><img src="<?php echo $this->baseUrl("/static/images/banner_4.jpg");?>" alt="Four slide"></a>
		        </div>
		        <div class="item">
		          <a href="<?php echo $this->baseUrl("/demo/shfw");?>"><img src="<?php echo $this->baseUrl("/static/images/banner_3.jpg");?>" alt="Five slide"></a>
		        </div>
		      </div>
		      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
		        <span class="glyphicon glyphicon-chevron-left"></span>
		        <span class="sr-only">Previous</span>
		      </a>
		      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
		        <span class="glyphicon glyphicon-chevron-right"></span>
		        <span class="sr-only">Next</span>
		      </a>
		    </div><!-- /.carousel -->
	  </div>
</div>
<div class="container"> 
	<div class="row row-item" id="ourcompay">
	   <h3>我们做什么</h3>
	   <div class="col-lg-4">
	      <p style="font-size: 100px;"><span class="glyphicon glyphicon-home"></span></p>
          <h2>全平台解决方案</h2>
          <p>我们开发优秀的、注重用户体验的网站、iOS应用和Android应用，帮你实现平台全覆盖，让你省心省力得到最先进的技术支持。</p>
        </div>
        <div class="col-lg-4">
          <p style="font-size: 100px;"><span class="glyphicon glyphicon-pencil"></span></p>
          <h2>高质量定制设计</h2>
          <p>我们用心设计，以用户为中心，范围涵盖交互设计、视觉设计、品牌设计，用设计让您的产品更上一层楼。</p>
        </div>
        <div class="col-lg-4">
        <p style="font-size: 100px;"><span class="glyphicon glyphicon-phone"></span></p>
          <h2>互联网产品咨询</h2>
          <p>想做产品不知如何下手？我们帮你制定合理的产品策略，让你脑中的想法变为现实，帮你在移动互联网时代抓住机会。</p>
        </div>
	</div>
	<div class="row row-item" id="ournews">
	   <h3>新闻动态</h3>
	   <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
	</div>
	<div class="row row-item" id="ourproducts">
	   <h3>产品中心与解决方案</h3>
	   <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
	</div>
	<div class="row row-item" id="ourprojects">
	   <h3>成功案例</h3>
	   <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
	</div>
	<div class="row row-item" id="joinus">
	   <h3>加入我们</h3>
	   <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-success" href="#" role="button">View details »</a></p>
        </div>
	</div>
      <div class="row">
			      <!-- Site footer -->
	     <div id="footer" class="row">
	     <hr>
	        <div class="col-md-12">
	            <p>&copy; 厦门中智信系统集成有限公司 2015</p>
	            <p>闽公安网安备15009999号-1∣闽ICP备15008888号-1</p>
	        </div>      

	     </div>
      </div>
    </div>
 </div>

    <?php echo $this->headScript();?>
  </body>
</html>