
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="中智信智慧社区,智慧社区,厦门智慧社区">
    <meta name="author" content="">
    <link rel="icon" href="/images/favicon.jpg">

    <title>中智信智慧社区</title>

    <!-- Bootstrap core CSS -->
    <link href="/jquery.plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="wrap">
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">eMegasys智慧社区管理系统-中智信智慧社区</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-logo"></span>&nbsp;eMegasys智慧社区管理系统---中智信智慧社区</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="//www.xmcii.com" target="_blank">关于我们</a></li>
            <li><a href="#">在线帮助</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>          
    </nav>
	<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar"> 
          <li><a href="http://www.54kaka.com/Devccweb/Login.aspx?u=13860157963&p=888888" target="_blank"><span class="glyphicon glyphicon-user"></span>智慧社区管理系统</a></li>       
            <li><a href="http://110.86.13.82:1500" target="_blank"><span class="glyphicon glyphicon-home"></span>智能建筑管理系统</a></li>            
            <li><a href="http://121.40.148.177:10808/xm9943/loginWx" target="_blank"><span class="glyphicon glyphicon-weixin"></span>社区微信管理系统</a></li>
            <li><a href="/shop"><span class="glyphicon glyphicon-shopping-cart"></span>中智信社区商家入口</a></li>
          </ul>
          <ul class="nav nav-sidebar borderd">
            <li><a href="#"><span class="glyphicon glyphicon-qq"></span>: 1355850897</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-phone-alt"></span>: 0592-5033910</a></li>            
          </ul>
          <ul class="nav">
            <li><img src="/images/QR_Code.png" class="img-responsive"></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <!-- Carousel
    ================================================== -->
		    <div id="myCarousel" class="carousel slide" data-ride="carousel">
		      <!-- Indicators -->
		      <ol class="carousel-indicators">
		        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		        <li data-target="#myCarousel" data-slide-to="1"></li>
		        <li data-target="#myCarousel" data-slide-to="2"></li>
		        <li data-target="#myCarousel" data-slide-to="3"></li>
		        <li data-target="#myCarousel" data-slide-to="4"></li>
		      </ol>
		      <div class="carousel-inner" role="listbox">
		        <div class="item active">
		          <a href="#"><img src="/images/banner_01.jpg" alt="First slide"></a>
<!-- 		          <div class="container"> -->
<!-- 		            <div class="carousel-caption"> -->
<!-- 		              <h1>中智信智慧社区</h1> -->
<!-- 		              <p>eMegasys智慧社区</p> -->
<!-- 		            </div> -->
<!-- 		          </div> -->
		        </div>
		        <div class="item">
		          <a href="/demo/sqgl"><img src="/images/banner_02.jpg" alt="Second slide"></a>
		          <!--<div class="container">
		            <div class="carousel-caption">
		              <h1>Another example headline.</h1>
		              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
		            </div>
		          </div> -->
		        </div>
		        <div class="item">
		          <a href="/demo/jzgl"><img src="/images/banner_03.jpg" alt="Third slide"></a>
		        </div>
		        <div class="item">
		          <a href="/demo/shfw"><img src="/images/banner_04.jpg" alt="Four slide"></a>
		        </div>
		        <div class="item">
		          <a href="/demo/shfw"><img src="/images/banner_05.jpg" alt="Five slide"></a>
		        </div>
		      </div>
		      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
		        <span class="glyphicon glyphicon-chevron-left"></span>
		        <span class="sr-only">Previous</span>
		      </a>
		      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
		        <span class="glyphicon glyphicon-chevron-right"></span>
		        <span class="sr-only">Next</span>
		      </a>
		    </div><!-- /.carousel -->
           <div class="row">
	        <div class="col-lg-6">
	        <h3>社区公告</h3>
	         <div class="item">
	         	<ul class="list-group">
	            	<li class="list-group-item"><a href="http://121.40.148.177/xm9943/article_twxx.php?id=45" target="_blank">欢乐社区行活动开启啦 </a></li>
	            	<li class="list-group-item"><a href="http://121.40.148.177/xm9943/article_twxx.php?id=46" target="_blank">水电费缴费公告</a></li>
	            	<li class="list-group-item"><a href="http://121.40.148.177/xm9943/article_twxx.php?id=47" target="_blank">关于高空抛物告示 </a></li>
	            </ul>        
	           <p><a class="btn btn-success" href="http://www.app667.com/xm9943/mobile/article_list.php?cat_id=19" role="button">更多 &raquo;</a></p>
	         </div>
	        </div>
	        <div class="col-lg-6">
	        <h3>社区活动</h3>
	         <div class="item">
	            <ul class="list-group">
	            	<li class="list-group-item"><a href="http://www.app667.com/xm9943/mobile/activity.php?id=5" target="_blank">2014平安居小区圣诞动感之夜 </a></li>
	            	<li class="list-group-item"><a href="http://www.app667.com/xm9943/mobile/activity.php?id=6" target="_blank">幸福家园首届亲子活动 </a></li>
	            	<li class="list-group-item"><a href="http://www.app667.com/xm9943/mobile/activity.php?id=7" target="_blank">幸福家园电脑门诊活动</a></li>
	            </ul>  
        
	           <p><a class="btn btn-success" href="#" role="button">更多 &raquo;</a></p>
	         </div>
	        </div>      
	      </div>
			      <!-- Site footer -->
	     <div id="footer" class="row">
	     <hr>
	        <div class="col-md-12">
	            <p>&copy; 厦门中智信系统集成有限公司 2015</p>
	            <p>闽公安网安备15009999号-1∣闽ICP备15008888号-1</p>
	        </div>      

	     </div>
        </div>
      </div>
    </div>
 </div>


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/jquery.plugins/jquery-1.11.1.min.js"></script>
    <script src="/jquery.plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>