<?php include 'functions.php';?>
<?php $LENGTH = 100;?>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="中智信智慧社区,智慧社区,厦门智慧社区">
    <meta name="author" content="">
    <link rel="icon" href="<?php echo $this->baseUrl("/static/images/favicon.jpg")?>">

    <title>中智信智慧社区-周边商家</title>

    <!-- Bootstrap core CSS -->
    <?php echo $this->headLink();?>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
 <body>
    <div class="wrap">
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">eMegasys智慧社区管理系统---周边商家</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-logo"></span>eMegasys智慧社区管理系统---周边商家</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="//www.xmcii.com" target="_blank">关于我们</a></li>
            <li><a href="#">在线帮助</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>          
    </nav>
	<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                      <span class="glyphicon glyphicon-shopping-cart"></span>周边商家</a>
                  </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                  <div class="panel-body">
                    <ul class="nav nav-sidebar">     
                        <li><a href="javascript:void(0);" id="shop_list"><span class="glyphicon glyphicon-list"></span>商家列表</a></li>       
                        <li><a href="javascript:void(0);" id="shop_add"><span class="glyphicon glyphicon-plus"></span>商家入驻</a></li>           
                      </ul>
                  </div>
                </div>
              </div>
             </div>
              <ul class="nav nav-sidebar">
                <li><a href="#"><span class="glyphicon glyphicon glyphicon-qq"></span>: 1355850897</a></li>
                <li><a href=""><span class="glyphicon glyphicon glyphicon-phone-alt"></span>: 0592-5033910</a></li>
              </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
         <div id="shop_container">
           <?php foreach ($this->shoplist as $shop) {
               if (strlen($shop["remark"]) > $LENGTH) {
                     $shop["remark"] = cutStr($shop["remark"], $LENGTH)."......";
            }?>
            <div class="media">
              <div class="media-left">
                <a href="#">
                  <img class="media-object" src="<?php echo $shop["shop_logo"]?>" style="width:96px; height:96px;">
                </a>
              </div>
              <div class="media-body">
                <h4 class="media-heading"><?php echo $shop["shop_name"]?></h4>
                <p><mark><?php echo $shop["busy_type"]?></mark></p>
                <address><?php echo $shop['address'];?></address>
                <p><?php echo $shop["remark"];?></p>
              </div>
            </div>
            <?php }?>
         </div>
          	    
			      <!-- Site footer -->
	     <div id="footer" class="row">
	     <hr>
	        <div class="col-md-12">
	            <p>&copy; 厦门中智信系统集成有限公司 2015</p>
	            <p>闽公安网安备15009999号-1∣闽ICP备15008888号-1</p>
	        </div>      

	     </div>
        </div>
      </div>
    </div>
 </div>


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

    <?php echo $this->headScript();?>

  </body>
</html>