<?php foreach ($this->shoplist as $shop) {?>

<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="<?php echo $shop["shop_logo"]?>" style="width:96px; height:96px;">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><?php echo $shop["shop_name"]?></h4>
    <p><mark><?php echo $shop["busy_type"]?></mark></p>
    <address><?php echo $shop['address'];?></address>
    <p><?php echo $shop["remark"];?></p>
  </div>
</div>
<?php }?>