<form role="form" id="shop_signin">
  <div class="form-group">
    <label for="shop_name">商家名称</label>
    <input type="text" class="form-control" id="shop_name" name="ShopName" placeholder="商家名称">
  </div>
  <div class="form-group">
    <label for="industry_type">行业类型</label>
    <input type="text" class="form-control" id="industry_type" name="IndustryType" placeholder="行业类型">
  </div>
  <div class="form-group">
  <label for="industry_type">shop_scale行业类型</label>
    <select class="form-control" name="ShopScale" id="shop_scale">
  <option>1-10人</option>
  <option>10-20人</option>
  <option>20-50人</option>
  <option>50-100人</option>
  <option>100人以上</option>
</select>
  </div>

  <button type="submit" class="btn btn-default">Submit</button>
</form>