<br /><br />
<div id="view-content">
	<?php 
	if ($this->result["error"] == 0) {?>
	<div class="alert alert-success alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      <p class="lead"><?php echo $this->result["message"];?></p>
    </div>
	<?php } else if ($this->result["error"] == 1){?>
	    <div class="alert alert-warning alert-dismissible fade in" role="alert">
	    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
	        <p class="lead">  <?php echo $this->result["message"];?></p>
	    </div>
	<?php } else {?>
		    <div class="alert alert-danger alert-dismissible fade in" role="alert">
	    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
	        <p class="lead">  <?php echo $this->result["message"];?></p>
	    </div>
	<?php }?>
</div>