
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="中智信智慧社区,智慧社区,厦门智慧社区">
    <meta name="author" content="">
    <link rel="icon" href="<?php echo $this->baseUrl("/static/images/favicon.jpg")?>">

    <title>中智信智慧社区</title>

    <?php echo $this->headLink();?>
    

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="wrap">
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">eMegasys智慧社区管理系统-中智信智慧社区</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-logo"></span>&nbsp;eMegasys智慧社区管理系统---中智信智慧社区</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="//www.xmcii.com" target="_blank">关于我们</a></li>
            <li><a href="#">在线帮助</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>          
    </nav>
	<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar"> 
          <li><a href="http://www.54kaka.com/Devccweb/Login.aspx?u=13860157963&p=888888" target="_blank"><span class="glyphicon glyphicon-user"></span>智慧社区管理系统</a></li>       
            <li><a href="http://110.86.13.82:1500" target="_blank"><span class="glyphicon glyphicon-home"></span>智能建筑管理系统</a></li>            
            <li><a href="http://121.40.148.177:10808/xm9943/loginWx" target="_blank"><span class="glyphicon glyphicon-weixin"></span>社区微信管理系统</a></li>
            <li><a href="<?php echo $this->baseUrl("/shop");?>"><span class="glyphicon glyphicon-shopping-cart"></span>中智信社区商家入口</a></li>
          </ul>
          <ul class="nav nav-sidebar borderd">
            <li><a href="#"><span class="glyphicon glyphicon-qq"></span>: 1355850897</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-phone-alt"></span>: 0592-5033910</a></li>            
          </ul>
          <ul class="nav">
            <li><img src="<?php echo $this->baseUrl("/static/images/QR_Code.png")?>" class="img-responsive"></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          
           <div id="view-content">
        	<p class="lead">eMegasys智能建筑管理系统将社区内防盗报警系统、楼宇对讲系统、周界报警系统、视频监控系统、电子巡更系统、门禁系统等进行有机的集成，建立对多子系统及其设备集中监视、协调控制和管理的综合系统，实现以下系统建设目标：
    <ul class="lead">
    <li>为社区内的环境舒适性提供保证；</li>
    <li>实现社区内安全防范与灾害防御能力的全面提高；</li>
    <li>实现社区设备的最佳运行，达到系统优化管理，最终实现节省能源；</li>
    <li>提供科学、合理的设备自动化管理程序，优化对设备运行的控制，降低系统运行和维护成本。</li>
     </ul>   	
        	
        	</p>
        </div>
        </div>
      </div>
    </div>
 </div>

 <?php echo $this->headScript();?>
  </body>
</html>

