
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="中智信智慧社区,智慧社区,厦门智慧社区">
    <meta name="author" content="">
    <link rel="icon" href="<?php echo $this->baseUrl("/static/images/favicon.jpg")?>">

    <title>中智信智慧社区</title>

    <?php echo $this->headLink();?>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="wrap">
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">eMegasys智慧社区管理系统-中智信智慧社区</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-logo"></span>&nbsp;eMegasys智慧社区管理系统---中智信智慧社区</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="//www.xmcii.com" target="_blank">关于我们</a></li>
            <li><a href="#">在线帮助</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>          
    </nav>
	<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar"> 
          <li><a href="http://www.54kaka.com/Devccweb/Login.aspx?u=13860157963&p=888888" target="_blank"><span class="glyphicon glyphicon-user"></span>智慧社区管理系统</a></li>       
            <li><a href="http://110.86.13.82:1500" target="_blank"><span class="glyphicon glyphicon-home"></span>智能建筑管理系统</a></li>            
            <li><a href="http://121.40.148.177:10808/xm9943/loginWx" target="_blank"><span class="glyphicon glyphicon-weixin"></span>社区微信管理系统</a></li>
            <li><a href="<?php echo $this->baseUrl("/shop");?>"><span class="glyphicon glyphicon-shopping-cart"></span>中智信社区商家入口</a></li>
          </ul>
          <ul class="nav nav-sidebar borderd">
            <li><a href="#"><span class="glyphicon glyphicon-qq"></span>: 1355850897</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-phone-alt"></span>: 0592-5033910</a></li>            
          </ul>
          <ul class="nav">
            <li><img src="<?php echo $this->baseUrl("/static/images/QR_Code.png")?>" class="img-responsive"></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          
           <div id="view-content">
        	<p class="lead">社区生活服务通过eMegasys社区微信管理系统微信平台进行全面整合，实现每月的水电缴费都能在微信提醒，所有的物业公告都能直接在微信上实时查看，预约维修也能在微信上一键完成。由此，物业也从一个冰冷的名词，变身成为更有温度的“贴身管家”。
微信智慧社区通过社区公众号平台，打通了微信缴费、消息推送、业主维护、生活服务、活动组织等涉及社区生活各方面的服务。业主只须关注社区微信公众帐号，再实名认证、成为社区用户，即可享受相关“贴身”服务。
除了住宅内的生活体验，繁忙的都市人也越来越关注社区的周边商业环境，包括餐饮、洗衣、健身、美容美甲等一系列配套设施成为了业主选择住宅的重要标准。而智慧社区通过微信平台这个整合的入口，吸引周边商家入驻，为业主提供优质的商品及服务。业主可以通过微信直接进行预约、购买，由周边商户上门服务或配送。如在公众号中搜索“美食”，立刻就能获得附近的餐馆、地址及口味说明等信息，并且可以直接下单外卖，实现足不出户的便利体验。
    借助微信智慧，物业不仅能够更及时、有效地为业主服务，还帮助许多业主找回了童年时邻里和睦相亲的时代温情，营造出儿时大院般安全、舒适、便捷的“有温度”社区生活。
        	</p>
        </div>
        </div>
      </div>
    </div>
 </div>

 <?php echo $this->headScript();?>
  </body>
</html>

