
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="中智信智慧社区,智慧社区,厦门智慧社区">
    <meta name="author" content="">
    <link rel="icon" href="<?php echo $this->baseUrl("/static/images/favicon.jpg")?>">

    <title>中智信智慧社区</title>

    <?php echo $this->headLink();?>
    

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="wrap">
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">eMegasys智慧社区管理系统-中智信智慧社区</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href=""><span class="glyphicon glyphicon-logo"></span>&nbsp;eMegasys智慧社区管理系统---中智信智慧社区</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="//www.xmcii.com" target="_blank">关于我们</a></li>
            <li><a href="#">在线帮助</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>          
    </nav>
	<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar"> 
          <li><a href="http://www.54kaka.com/Devccweb/Login.aspx?u=13860157963&p=888888" target="_blank"><span class="glyphicon glyphicon-user"></span>智慧社区管理系统</a></li>       
            <li><a href="http://110.86.13.82:1500" target="_blank"><span class="glyphicon glyphicon-home"></span>智能建筑管理系统</a></li>            
            <li><a href="http://121.40.148.177:10808/xm9943/loginWx" target="_blank"><span class="glyphicon glyphicon-weixin"></span>社区微信管理系统</a></li>
            <li><a href="<?php echo $this->baseUrl("/shop");?>"><span class="glyphicon glyphicon-shopping-cart"></span>中智信社区商家入口</a></li>
          </ul>
          <ul class="nav nav-sidebar borderd">
            <li><a href="#"><span class="glyphicon glyphicon-qq"></span>: 1355850897</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-phone-alt"></span>: 0592-5033910</a></li>            
          </ul>
          <ul class="nav">
            <li><img src="<?php echo $this->baseUrl("/static/images/QR_Code.png")?>" class="img-responsive"></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          
           <div id="view-content">
        	<p class="lead">中智信智慧社区管理系统由eMegasys智能建筑管理系统、eMegasys社区微信集成系统及eMegasys智慧社区管理系统三大部分组成。
智慧社区管理系统以eMegasys智能建筑管理系统为基础，实现对设备的统一管理控制及跨子系统联动等功能；以微信公众号为载体，实现社区用户与社区用户之间，物业与业主之间、社区用户与商家之间文字、图片、语音、视频互动。并通过微信集成系统的二次开发，集成周边微信，为社区用户提供居家生活、安全、购物、饮食、健康、教育等服务；通过eMegasys智慧社区管理系统，综合管理社区智能化系统的设备报警情况及居民生活繁琐事项。
中智信智慧社区管理系统解决方案提供对社区智能化系统集中管理、社区智能服务、智慧物业及社区微信平台等方面的服务，全面提升社区智慧化管理服务水平，为社区生态体系参与者打造一个安全、舒适、便捷、和谐的生产、生活、管理、服务环境！
        	
        	
        	</p>
        </div>
        </div>
      </div>
    </div>
 </div>
 <?php echo $this->headScript();?>
  </body>
</html>

